### ISSUE TITLE
set_width in_width and group_width has used before assign a value

### ISSUE THREAD

**Issue by 32l** [sseung0703/Autoslim_TF2#2]

**Comment by sseung0703** [comment]
Could you give me more information about your problem?
I tested the latest code again and there was no problem.

**Comment by 32l** [comment]
Traceback (most recent call last):
  File "train_w_slimming.py", line 151, in <module>
    test_step,  test_loss,  test_accuracy = op_util.Slimmable_optimizer(args, model, args.weight_decay, args.learning_rate)
  File "/home/liaoting/proj/Autoslim_TF2/op_util.py", line 54, in Slimmable_optimizer
    slim_util.set_width(args.arch, model, full_width)
  File "/home/liaoting/proj/Autoslim_TF2/slim_util.py", line 93, in set_width
    Di = None if layer.type == 'input' else in_width
UnboundLocalError: local variable 'in_width' referenced before assignment

**Comment by sseung0703** [comment]
Did you modify a network? If you did, you should also modify "get_initial_width" and "set_width" in slim_util yourself.

**Comment by 32l** [comment]
No， i hadn't  modify your code,  i just run mobilev2 as your's default args.

**Comment by sseung0703** [comment]
I re-tested my code, but there is no problem. could you try again using the latest code?

**Comment by 32l** [comment]
yes， i used the latest code， my env is python2.7 and tf 2.1.0.  Obviously,  I think we need to give 'in_width' and 'group_width'  values before we use them in set_width func.

**Comment by sseung0703** [comment]
This issue may be related to env. I tested in python 3.7. "in_width" and "group_width" are given before they referenced.

**Comment by 32l** [comment]
ok, BTW, Thanks for your good job!
